:title: Java Enterprise'ish development without hassle
:subtitle: Approach Java web development without over-engineered hassle, as there are simpler approaches than JPA + EJB + JSF to build the web tier of your application.

== {title}

> {subtitle}

=== Abstract

This happens in every community: You don’t need Rails, to build a web application in Ruby. You don’t need templating engine for PHP - PHP is a templating language! We over engineer and over engineer, again and again.

Same happens in Java. Hibernate + EJB + JSF is not the only blessed stack for development of web application… one can argue it’s the worst. Same with Spring; no longer lighweight, no so robust - still powerful but not necessary the easiest. So what are the options for an average Java developer?

In this talk I’ll walk through multiple options, for modern Java web development: easy, quick, flexible and still state of an art. Starting for just obvious unknowns like embedded jetty, though micro pure-webframeworks, smaller and bigger swiss army knifes, which try to promise both: cover most of the application stack, still keeping things robust.

=== Testimonials

The feedback after Confitura 2014 surveys conference

* "Very good presentation. On one hand effortless, on the other - with a lot of easy to remember information"
* "I wish all presentations looked like this: quick run through some theory + lookup how the code looks in practice"
* "Very inspiring presentation"

=== Videos

https://www.youtube.com/watch?v=orGJZuPYgZ8[Confitura2014 - in Polish]

=== Additional resources

* https://speakerdeck.com/kubamarchwicki/jee-without-hassle-pl[PDF Slides] - in Polish
* http://htmlpreview.github.io/?https://raw.githubusercontent.com/kubamarchwicki/presentations/master/jee-without-hassle/slides-pl.html[HTML slides] - in Polish
* https://github.com/kubamarchwicki/presentations/tree/master/jee-without-hassle[Slides source in *asciidoctor*]
* https://github.com/kubamarchwicki/micro-java/[Code examples @ GitHub]
