---
layout: post
categories: posts
title: ! 'TypeScript: Setting up an IDE and working environment - part II'
excerpt: Every setup evolves. In the past six months mine evolved from Sublime to Atom editor. Here is what's needed to start TypeScripting with Atom Editor
tags: typescript
---
:experimental:

I've been trying the link:http://atom.io[Atom Editor] multiple times, trying to switch from Sublime (my default text editing environment). I always found it not mature enough. I've recently given it another try - this time successfully. So it's time for the plugin setup of my TypeScript IDE.

== It's all about plugins

Some things haven't changes: still there is not need for `npm install -g typescript` - we can keep everything inside the editor. The full TypeScript support comes with multiple plugins.

link:https://atom.io/packages/atom-typescript[atom-typescript]::
It's advertised as `The only TypeScript plugin you will ever need` and it's quite so. It handles auto completion, compilation on save - good starting point for us to be productive.

link:https://atom.io/packages/linter-tslint[linter-tslint]::
It's optional, but provides a good hint for consistency in your TypeScript files. Things like semicolons, are optional - but it's good to either have them or not. Lint will take care of those.

link:https://atom.io/packages/script[script]::
Just to _"Run code in Atom"_; when it comes to some code snippets it's worth to be able to evaluate if straight away in console (especially when you just hack around in the learning process). _Script_ package gives you a helping hand here.

That's about it. I know this it not a production environment, shipping IDE created `js` files is like shipping a `jar` file created through `File > Export` in Eclipse. Nonetheless, it's enough to start getting better with language. Other tools will come with time.
