language: ruby
branches:
  only:
  - devel
env:
  global:
    secure: OHXFuMxg9GojFdf4jy+l7nSb9LrL0aHuqLm7S4HwFfXBTsfKPxlgGz8jQIBODdq+NV7tPbLfcXW0D7VYR8kTdH+kBITnrLxQX9g9gAs5e8JFlyni8LWFPdm+isibEVlFsyZVHJX4RQzJ4DKVMs8reMmbiueGxEQyUYhOQEo+P2o=
rvm:
- 2.2.0
sudo: false
before_script:
- git config --global user.name 'Travis CI'
- git config --global user.email 'kuba.marchwicki+travis@gmail.com'
script: bundle exec rake deploy
