language: ruby

branches:
  only:
  - devel

env:
  global:
    secure: OUDk75GVgZMKfDHM7WKNXLWlzEFKelIapWddUmVmVN4KPw57OtHt91cyNg+ETDdQsJL/G8zE8VRArUv9lbcTaCqN+yydhYOMn6WAwhhplStjx912opWD9Ra1i3nAxuQYHaxQacnOnRWo5g9A7JJ94EvtI2GNu6GQlpDMAsCV7/Y=


rvm:
  - 2.2.0

sudo: false

before_script:
  - git config --global user.name 'Jekyll'
  - git config --global user.email ''
script: JEKYLL_ENV=production bundle exec rake deploy
