language: ruby
branches:
  only:
  - devel
rvm:
- 2.4.2
sudo: false
before_script:
- git config --global user.name 'Travis CI'
- git config --global user.email 'kuba.marchwicki+travis@gmail.com'
script: JEKYLL_ENV=production bundle exec rake deploy
env:
  global:
    secure: "u8aIe/27peyopiU3BX+JaF8AQ+sX04n9M490azsYlVH4pVv/91aXQleeKRdR5LRjiMq7W6ON4ojPSIyywrn1PWimdqeUqNnwFLYMt7QdQK/FFacuymrXwFbv679W/7bUIH3jOA4KDXm8yqZL30pAOE+EsbYDDOu1o66qYs7/wy8="
