language: ruby

branches:
  only:
  - devel

env:
  global:
    secure: AKndo/VJUBbuC3ZvH4zul9APq9uL7a0IxJBYWc+kQ5o4/ceX8Q9a7I2TnsTVwhK2/z6cZuvwMtoDrBJVwedcetDBKpAtSwyKXGZmz4CUYtL2HX+Jq7x0vic5gaUqBZtTfQNBo8jHyWeDV2XkRnGz5sQzSbGDB1ss8yxbN7evLyg=

rvm:
  - 2.2.0

sudo: false

script: JEKYLL_ENV=production bundle exec rake deploy