# Site settings
title: Notepack 
email: "kuba.marchwicki+blog@gmail.com"
description: "A randomized pack of notes" 
baseurl: ""
url: "http://www.marchwicki.pl"
twitter_username: kubem 
github_username: kubamarchwicki

# Build settings
markdown: kramdown
permalink: pretty

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay
    - coderay-css=style
