# Site settings
title: Notepack
email: "kuba.marchwicki+blog@gmail.com"
description: "A randomized pack of notes"
baseurl: ""
url: "http://jakub.marchwicki.pl"
twitter_username: kubem
github_username: kubamarchwicki
linkedin_username: kubamarchwicki

# https://help.github.com/articles/redirects-on-github-pages

analytics:
  account: UA-439480-4

# Build settings
markdown: kramdown
permalink: pretty

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=highlightjs
