# Site settings
title: Notepack
email: "kuba.marchwicki+blog@gmail.com"
description: "A randomized pack of notes"
baseurl: ""
url: "http://jakub.marchwicki.pl"
twitter_username: kubem
github_username: kubamarchwicki
linkedin_username: kubamarchwicki

gems:
  - jekyll-redirect-from
  - jekyll-asciidoc

analytics:
  account: UA-439480-4

# Build settings
markdown: kramdown
permalink: pretty

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

static_pages:
#  - title: Consultancy
#    url: /offer/
#    css-icon: star
  - title: All posts
    url: /posts/
    css-icon: page-multiple
  - title: All speaking
    url: /speaking/
    css-icon: microphone
  - title: Consultancy
    url: /consultancy/
    css-icon: comments


asciidoctor:
  safe: unsafe
  attributes:
    - hardbreaks!
    - source-highlighter=coderay
