= {title}
:title: GeeCON Reactive 2016 - in Sopot this September
:page-layout: post
:page-categories: [posts]
:page-excerpt: What's the story behind the GeeCON Reactive? And why it's worth checking out.

It has been official since the big GeeCON in May in Kraków: we are doing another GeeCON event in Sopot. AGAIN!

*Update 2016-08-01*. This is the first part of a two part series. Read the agenda follow up part: link:{% post_url posts/2016-08-01-reactive-geecon-part-ii %}[GeeCON Reactive 2016 - part II - Agenda]

++++
<blockquote class="twitter-tweet" align="center"><p>So it's official, there is no way back. <a href="https://twitter.com/hashtag/geecon?src=hash">#geecon</a> <a href="https://twitter.com/hashtag/reactive?src=hash">#reactive</a> <a href="https://twitter.com/hashtag/sopot?src=hash">#sopot</a> will take place on 9th of September 2016</p>— jakub marchwicki (@kubem) <a href="https://twitter.com/kubem/status/731127144265453568">May 13, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

Last year, the GeeCON Microservices went good, we enjoyed it, we've got a positive feedback. So this year we decided to challenge ourselves again.

Obviously, not about microservices - it's not hip enough anymore. We decided to pivot GeeCON Sopot towards a `Buzzword Driven Conference`: take yet another industry buzzword and distill it into its tiniest detail. Possibly - a different buzzword every year.

So what's this year about? You guessed right - this year's theme is *reactive* and we are bringing the link:http://2016.reactive.geecon.org[GeeCON Reactive] to the GeeCON family.

== A single track

http://2016.reactive.geecon.org/[GeeCON Reactive] is a single day, single track conference. link:{% post_url posts/2015-08-05-microservice-geecon %}#a-single-track[As it was last year], for exactly the same reasons: our ambition wasn't to bring you largest number of speakers, enormous amount of tracks. The rationale was different: focus on a single topic and cover it from multiple perspectives.

== No call for papers

We know this is a controversial topic. It was also a hard decision for us - not to give a shout out to the community. We did the job of curating the agenda and bringing most valuable speakers we could think of.

Like last year we want to look at reactive from different angels, to show the impact of the whole reactive concept on our industry, on how we are (or will be) building our applications / systems / solutions.

== Location

We have "if it works don't fix it" mantra deep in our hearts, hence  http://2016.reactive.geecon.org/[GeeCON Reactive] will remain the only conference (at least in Poland) with only 200 meters (measured) between you and the sandy beach.

Last year people had lunch at the beach, a refreshing brief of sea air between the sessions. Expect exactly the same this year - weather is pre-booked as well ;-)

Venue stays the same: link:http://2016.reactive.geecon.org/practical/[The Multikino Sopot] is a small and enjoyable cinema. We value quality over quantity - a cozy venue, great talks, quality food. That's our definition of work / relax balance.

== Sessions

Last, but not least: sessions. We will not reveal everything - just give you a feeling what to expect with the first three sessions.

We are starting with link:twitter.com/graham_jp[Jonathan Graham] and his very gentle introduction to reactive systems. If you've never given yourself time to understand what reactive is about - this is a session for you. If you do understand it but struggle with describing it to your grandma - this session is also for you. In other word: reactive 101.

This is to be followed by link:https://twitter.com/ktosopl[Konrad Malawski] session, drilling down the Reactive Streams. There is no better person to do it than the author of Reactive Streams TCK and Akka core team member. Expect a deep technical insight.

To close of the first batch, we invited link:https://twitter.com/robertharrop[Rob Harrop], CTO of Skipjaq and a co-founder of SpringSource (in his past-life). In his Going Reactive talk he will show what it means for applications to become reactive, not only on the code level but beyond; identify patterns, decouple components and more.

== More to come...

From now on, every other week we will be revealing more http://2016.reactive.geecon.org/[GeeCON Reactive] sessions - some goodies are still to come.

As you can see from this first teaser - we are taking the concept pretty seriously. This is only the first batch and some more speakers are already "revealed" on the http://2016.reactive.geecon.org/[website]. Talks and titles are still to come so stay tuned.
