---
title: Characterization tests with junit
layout: post
categories: posts
---

== What are characterization tests and why care?

=== Context

I've recently engaged myself into upgraded our internal, vendor provided, not supported anymore HR application.
As we've been refactoring one of our internal systems (upgrade from Rails 1.8 to 3.0) - it impacted a few systems nearby. Mostly due to the way Rails handled SOAP web services, which were the basis of the integration; the WSDL needed changing significantly and thus needed the HR system client classes.

The whole idea was to replace existing axis stubs with new classes, keeping the interfaces backwards compatible. Rather simple task but not in this context: the app appeared to be a Java JSP web application with literally 10 class files and hundreds of JSP files with tons of logic in it (500+ lines per each JSP was a standard). A Java application in a bad PHP style.

=== How to proceed

From the application logs (around 150MB per week, as nobody though of turning of global DEBUG in log4j.properties) I could be able to figure out what classes were responsible for the web service communication - that was the starting point.

The plan was to adhere to keep it working principle:
* extract the classes into a single jar
* replace the classes with a lib
* replace the lib with a new stub and client

Few simple tasks to do. But what bothered me was how to make sure that the data structures before and after the changes are still the same. This was especially important, because the app was very fragile (to such extent that changing the order of XML tags in the SOAP request actually mattered).

=== Actual tests

This is when I was brought to characterization tests. I needed to describe the existing application and after each step, test the changes against the model (my benchmark). Hence, the flow looked pretty much like this:

* analyze the class / method in subject, gain the conceptual understanding
* invoke the method within tests
* log complete output / compare the output with existing log output

When the tests went green - I felt much safer. I know this is far from ideal testing method, but at least it has given a little of confidence in the baby steps I was making.

== Where to start

Ok, that was theory. Question is how to actually implement such test; recordings and assertions. The whole thing is actually pretty damn easy, especially with the last releases of JUnit. We will be leveraging Rule (ClassRule annotation to be precise) and the whole concept of TestRules.
