:title: Managing a team vs. babysitting kids
:subtitle: any differences?

== {title}

> {subtitle}

=== Abstract

Have you been promoted from developer to manager recently and feeling lost? Or You’re in programming-power-point business for years and still got surprised by your team? Don’t worry - we’ve been there too and we’re eager to share our experience. And we also have kids...

Being a manager is on one hand attending dozen of courses, hundreds of read books: things you learn at the MBA studies, things you won’t learn at the MBA, psychology in business, human resources, coaching - list goes on and on...
On the other hand, people say just be a good person, be consistent, believe in others - that will do. Managing people is as easy as kid’s play…
So which is right, which is a way to go?

At this session you will learn how to practically apply a couple of management principles which set up a fundament for managing developers. We will put them to test with real life examples, how we succeeded or how we failed. These obviously are not silver bullets, these work in a certain context - which we won’t miss in our stories.

Are these a key, to make manager’s life so much easier? Are you interested in finding that key?

== Videos

.Devoxx.pl 2016
video::RaXTXXEcjU0[youtube, width=640, height=480]

////
Wersja Polska
Title: Niańczenie programistów vs. zarządzanie dziećmi

Czy zostałeś ostatnio awansowany z dewelopera na menedżera i czujesz się zagubiony? Albo zajmujesz się programowaniem w power poincie od lat i nadal jesteś zaskakiwany przez swój zespół? Nie martw się – też to przechodziliśmy i chętnie podzielimy się doświadczeniem. Mamy także dzieci…

Bycie managerem wiąże się z jednej strony z uczestnictwem w wielu kursach, setkami książek: rzeczy, które nauczyłeś się na studiach MBA, rzeczy których nie nauczysz się na MBA, psychologia w biznesie, zasoby ludzkie, coaching - lista tylko rośnie…

Z drugiej strony, mówi się po prostu bądź dobra osobą, bądź spójny, uwierz w innych - to wystarczy. Zarządzanie ludźmi jest proste jak drut…

Które podejście jest właściwe?

Podczas spotkania dowiesz się, jak w praktyce zastosować kilka zasad zarządzania, które tworzą podstawy zarządzania deweloperami. Zweryfikujemy je na realnych przykładach z życia, czy sprawdziły się czy nie. Te zasady nie są lekiem na całe zło, one działają w pewnym kontekście, którego w naszych historiach nie zabraknie.

Czy powyższe jest sekretem do uczynienia życia managera dużo bardziej prostym? Czy jesteś zainteresowany znalezieniem tego klucza?

////
