:title: Maven - your ultimate CD tool
:subtitle: We love new tools, but there are these, oldie but goldie. They do their job - so why not explore it further; Maven as a Continuous Delivery tool.

== {title}

> {subtitle}

=== Abstract

Maven. Everybody uses it. Everybody hates it (classic love hate relationship).
Embracing it ain't easy - but once done, it becomes a golden hammer.

This title is a bit flame'ish - for a reason.
In this showcase session I'll complete a continuous delivery pipeline of a multi module project with pure Maven (+ plugins).
Once that is done - adding a Jenkins (I mean a scheduler) is as easy as 1-2-3.

So if you've been using Maven a bit but never gave it enough time - this is a talk for you!


////
This talk is based on multiple training sessions, where I was introducing Maven to both developers teams as well as ops teams.

The session is a live coding (ekhmmm - live XMLing) session where I Mavenizing different elements of a project.

1. Simple WAR assembly
2. Using resources and Servlet 3.0 spec to combine frontend (JS / node) with an application
3. local / remote deployments
4. integration testing
5. release / distribution management
6. docker'zing the application (as a part of Maven lifecycle)
////
