:title: 6 tips for you JavaEE project be less depresing
:subtitle: Mind the gaps in the JavaEE environment and try to fix it with some decent libraries, different approaches - bringing it closer towards modern web development.

== {title}

> {subtitle}

=== Abstract

People are stuck to JavaEE not because they love it, but because it was in their work place, it is still there and will be there long after they leave. While many engineers think about going reactive, functional (or any other fashionable buzzword), some are still struggling how to migrate weblogic9 to weblogic12 and move from Java not supported for past 8 years (like Java 1.4) to the one not supported only just for a year (Java7).

While their live can be miserable - there are means for them to win JavaEE back, have fun again. It still won't be a super duper modern framework, it won't have all the latest pre-summer goodies, won't be a sweet language (full of syntactic sugar candies), but a solid set of tools that can make development pleasure again (kind of).

In the modern JavaEE you are no logger limited to the 'standard' but you can take advantage of limitless set tools and libraries. For some people it will still be the bad and ugly JavaEE, "feels like Spring but n-years ago", "Spring wannabe in the poor's man land" - that's true. But if you can't win Them (and let's be honest - in most enterprise'ish environments you can't win Them), join them! And have you JavaEE the way You like it.

This presentation will walk through multiple libraries that can help you change your project from "This is The Standard Even If It Doesn't Fit" way to a something far more approachable, where your tools doesn't feel like the Maslow's Hammer. I'll be sharing some experience from multiple trainings, projects and refactorings of old-but-still-in-production JavaEE applications and tools we used to get away The Standard.

=== Additional resources

* https://speakerdeck.com/kubamarchwicki/winning-javaee-back[PDF Slides]
* https://github.com/kubamarchwicki/winning-javaee-back/blob/master/slides/src/slides.adoc[Slides source in *asciidoctor*]
* https://github.com/kubamarchwicki/winning-javaee-back/[Code examples @ GitHub]

////
Wersja Polska

JavaEE - nie musi byc tak smutna jak się Tobie wydaje

Ludzie wybierają JavaEE nie dlatego że kochają tą technologie, ale dlatego że po prostu jest tam gdzie akuratnie pracują (i pewnie jeszcze będzie długo po tym jak odejdą). Nazwijmy to po imieniu: ludzie grzęzną w projektach JavaEE. W sytuacji gdy niektórzy programiści zastanawiają się na monadami, monoidami, programowaniem funkcyjnym (lub jakąkolwiek inną modą), niektórzy wciąż mają problem z migracją weblogic9 na weblogic12 i przejściem z Javy (nie wspieranej przez ostatnie 8 lat - jak Java 1.4) na Javę nie wspieraną tylko od roku (Java7).

Ich życie wydaje się być smutne - ale uwierzcie mi są sposoby na odrobinę frajdy nawet w projektach JavaEE. To wciąż nie będzie super-duper nowoczesny framework, pełen niesamowitych nowości, napisanych w słodkim języku (słodkim od wszystkich syntaktycznych cukiereczków) - ale zestaw narzędzi które spowodują że praca może znowu stanie się przyjemnością.

Od dłuższego czasu JavaEE to nie jest już 'tylko i wyłącznie błogosławiony standard' - możemy korzystać z innych narzędzi i bibliotek. Dla niektórych to wciąż będzie to ta zła i brzydka JavaEE, "wyglądająca jak Spring przed dekady", "Spring wannabe's" - to prawda. Ale gdy z rzeczywistością nie da się walczyć - trzeba ją polubić.

W tej prezentacji pokażę że JavaEE da się lubić - że można zamienić projektu "mamy standard mimo że w ogóle nie pasuje" na coś lepiej dopasowanego, gdzie nasza praca to coś więcej niż pasmo codziennych udręk. Materiał tej sesji to doświadczenie kilku projektów JEE, szkoleń, projektów J2EE które udało się wyprowadzić "na ludzi".


////

////

Testimonials:
* http://www.mberkan.pl/2016/04/15/konferencja-4developers-2016/
* http://namiekko.pl/2016/04/14/o-roznicy-pomiedzy-konferencja-naukowa-a-programistyczna-czyli-wyprawilam-sie-zdzieckiem-i-mezem-na-4developers/

////

////
## Outline

As outined in the description, this presentation will walk through multiple libraries that can help you change your project from "This is The Standard Even If It Doesn't Fit" way to a something far more approachable.

In details:
* Know your stack; recap of things that are supported by most vendors, but still not present in many projects: async processing (without JMS), events and observables, standardized dependency injection
* Limit the boiler plate - introduction of Apache DeltaSpike (CDI extensions)
* Go beyond The Standard (not only JPA) - persistence with jOOQ or jDBI (or other popular libs) smoothly integrated in JEE environment
* Web beyond JSF. MVC part of spec. Integrating other web frameworks. Web without server side frameworks
* Smooth integration with other modern goodies (nodejs development), cause we always need to lookup old stuff
* Don't be limited to server-side MVC or JSF, or Servlets; managing UI through single page applications or MVC 1.0

## Outline.

These are topic I'd like to tackle.

* Fixed asynchronous without JMS (@Asynchronous annotation, Executors) - coming out from old-days threads hacks
* Data access layer: while JPA is good, it's not good for everything. JOOQ, jDBI and others smoothly integrated in JEE environment
* Web beyond JSF. MVC part of spec. Integrating other web frameworks. Web without server side frameworks
* Smooth integration with other modern goodies, cause we always need to lookup old stuff

## Various

Templates Mustache

* https://github.com/spullara/mustache.java
* Mustache: https://github.com/spullara/mustache.java - just for templating
* https://jknack.github.io/handlebars.java/loader.html
*     http://stackoverflow.com/questions/30110342/how-to-create-a-restful-application-using-jersey-and-mustache-template-engine

Templates Thymeleaf

* http://spring-java-ee.blogspot.com/2014/12/trying-thymeleaf-for-one-day-why-is-it.html
* https://dzone.com/articles/thymeleaf-with-javaee-8

MVC 1.0

* http://forum.thymeleaf.org/MVC-1-0-Java-EE-8-Thymeleaf-td4029067.html
* http://vytas.io/blog/java/Java-EE-8-MVC-with-Ozark-and-Apache-Tomcat/
* http://squeakytech.blogspot.de/2015/03/getting-started-with-jee-8-mvc.html

Stateless MVC for JavaEE

* https://struts.apache.org/docs/cdi-plugin.html

## So you think standards will save you - on differences between JEE containers

* injections in servlets (@EJB vs @Inject)
* injection of validator (@Inject vs @Resource)
* JSON (jettison vs jackson)
  - output message. arrays vs objects
  - @JsonIgnore

* JAX-RS -> configuration in Glasshfish, JBoss7
  * simlar to persistence.xml - we treat web.xml as a similar configuration
   XML is Java DSL afterall

* wiring multiple EJB with the same interface (open ejb vs jboss) - CDI standardization
* JNDI tree (JEE6 standarisation java:global/[artifact]/[beanname]

* Timer. 5 seconds is not 5 seconds
* Stateful vs Stateless and pool implementation https://github.com/javaee-samples/javaee7-samples/issues/205#issuecomment-38309429
* EntityManager injection

```

    @PersistenceContext(unitName = "JPA_DB4B_LOCAL")
    EntityManager em;  //weblogic

    @PersistenceContext
    EntityManager em;  //anywhere else
```


Cat pictures 

http://i.giphy.com/Ov5NiLVXT8JEc.gif

////
