= {title}
:title: Microservices workshop
:page-layout: post
:page-categories: [consultancy]
:page-comments: false
:page-permalink: /consultancy/microservices/

Microservies. Everybody is talking about microservices. Everybody says they do microservces. The definition of microservice architecture is quite broad and vague: functional decoupling into discrete services, hence the number of approaches, with different flavors and implementations is so great - everybody can do microservices differently.

Fact is, not everything needs to stand as autonomous Java applications communicating over HTTP with JSON as a transport language. Different architectures compromises different elements - which is great and show
the true flexibility of the approach. However, regardless of implementation there is a set of practices that should be present in all solutions.

.What you will learn
During the workshop we will distill, name a couple of patterns and play with an example implementation of:

* service registers and discovery
* circuit breakers
* consumer driven contracts
* centralized logging and monitoring
* approaches in front-end web architecture (API gateway)

== Get in touch

I'm happy to talk. I can be reached via link:http://twitter.com/kubem[twitter], link:https://www.linkedin.com/in/kubamarchwicki[linkedin] or traditionally through link:mailto:kuba(d0t)marchwicki(at)gmail(d0t).com[kuba.marchwicki at gmail.com]
